cleandata$plantSp = tolower(cleandata$plantSp)
plantFreq=data.frame(table(dplyr::select(cleandata, plantSp)))
cleandata$clean_plantSp = cleandata$plantSp

cleandata$clean_plantSp = gsub("acer saccharum", "sugar maple", cleandata$clean_plantSp)
cleandata$clean_plantSp= gsub("sugar maple ", "sugar maple", cleandata$clean_plantSp)
cleandata$clean_plantSp[cleandata$clean_plantSp == 'alder'] = "hazel alder"
cleandata$clean_plantSp= gsub("hazel alder", "Hazel alder", cleandata$clean_plantSp)
cleandata$clean_plantSp= gsub("american basswood", "American basswood", cleandata$clean_plantSp)
cleandata$clean_plantSp= gsub("basswood", "American basswood", cleandata$clean_plantSp)
cleandata$clean_plantSp= gsub("american beech", "American beech", cleandata$clean_plantSp)
cleandata$clean_plantSp= gsub("american beech ", "American beech", cleandata$clean_plantSp)
cleandata$clean_plantSp= gsub("beech", "American beech", cleandata$clean_plantSp)
cleandata$clean_plantSp= gsub("american bladdernut", "American bladdernut", cleandata$clean_plantSp)
cleandata$clean_plantSp= gsub("bladdernut", "American bladdernut", cleandata$clean_plantSp)
cleandata$clean_plantSp= gsub("american chestnut", "American chestnut", cleandata$clean_plantSp)
cleandata$clean_plantSp= gsub("american holly ", "American holly", cleandata$clean_plantSp)
cleandata$clean_plantSp= gsub("american holly", "American holly", cleandata$clean_plantSp)
cleandata$clean_plantSp= gsub("carpinus caroliniana", "American hornbeam", cleandata$clean_plantSp)
cleandata$clean_plantSp= gsub("american hornbeam ", "American hornbeam", cleandata$clean_plantSp)
cleandata$clean_plantSp= gsub("american hornbeam", "American hornbeam", cleandata$clean_plantSp)
cleandata$clean_plantSp= gsub("american sycamore", "American sycamore", cleandata$clean_plantSp)
cleandata$clean_plantSp= gsub("arsp", "Devil's walkingstick", cleandata$clean_plantSp)
cleandata$clean_plantSp= gsub("devil's walking stick", "Devil's walkingstick", cleandata$clean_plantSp)
cleandata$clean_plantSp= gsub("devil's walkingstick", "Devil's walkingstick", cleandata$clean_plantSp)
cleandata$clean_plantSp= gsub("devil's-walking-sticl", "Devil's walkingstick", cleandata$clean_plantSp)
cleandata$clean_plantSp= gsub("devils claw", "Devil's walkingstick", cleandata$clean_plantSp)
cleandata$clean_plantSp= gsub("devils walking stick", "Devil's walkingstick", cleandata$clean_plantSp)
cleandata$clean_plantSp= gsub("devils-walkingstick", "Devil's walkingstick", cleandata$clean_plantSp)
cleandata$clean_plantSp= gsub("bear huckleberry", "Bear huckleberry", cleandata$clean_plantSp)                  
cleandata$clean_plantSp= gsub("bitternut hickory", "Bitternut hickory", cleandata$clean_plantSp) 
cleandata$clean_plantSp= gsub("butternut hickory", "Bitternut hickory", cleandata$clean_plantSp) 
cleandata$clean_plantSp= gsub("black gum", "Black gum", cleandata$clean_plantSp)
cleandata$clean_plantSp= gsub("black oak", "Black oak", cleandata$clean_plantSp) 
cleandata$clean_plantSp= gsub("black willow", "Black oak", cleandata$clean_plantSp)
cleandata$clean_plantSp= gsub("black willow ", "Black willow", cleandata$clean_plantSp)
cleandata$clean_plantSp= gsub("willow", "Black willow", cleandata$clean_plantSp)
cleandata$clean_plantSp= gsub("wilow", "Black willow", cleandata$clean_plantSp)
cleandata$clean_plantSp= gsub("box elder", "Box elder", cleandata$clean_plantSp)
cleandata$clean_plantSp= gsub("box elder ", "Box elder", cleandata$clean_plantSp)
cleandata$clean_plantSp= gsub("buffalo nut", "Buffalo nut", cleandata$clean_plantSp)
cleandata$clean_plantSp= gsub("acarolina ash", "Carolina ash", cleandata$clean_plantSp)
cleandata$clean_plantSp= gsub("carolina ash", "Carolina ash", cleandata$clean_plantSp)
cleandata$clean_plantSp= gsub("carolina ash ", "Carolina ash", cleandata$clean_plantSp)
cleandata$clean_plantSp= gsub("carolina silver", "Carolina silverbell", cleandata$clean_plantSp)
cleandata$clean_plantSp= gsub("carolina silver bell", "Carolina silverbell", cleandata$clean_plantSp)
cleandata$clean_plantSp= gsub("carolina silverbell", "Carolina silverbell", cleandata$clean_plantSp)
cleandata$clean_plantSp= gsub("silverbell", "Carolina silverbell", cleandata$clean_plantSp)
cleandata$clean_plantSp= gsub("chalk mape", "Chalk maple", cleandata$clean_plantSp)
cleandata$clean_plantSp= gsub("chalk maple", "Chalk maple", cleandata$clean_plantSp)
cleandata$clean_plantSp= gsub("chestnut oak", "Chestnut oak", cleandata$clean_plantSp)
cleandata$clean_plantSp= gsub("common persimmon", "Common persimmon", cleandata$clean_plantSp)
cleandata$clean_plantSp= gsub("persimmon", "Common persimmon", cleandata$clean_plantSp)
cleandata$clean_plantSp= gsub("perssimon", "Common persimmon", cleandata$clean_plantSp)
cleandata$clean_plantSp= gsub("dwarf paw paw", "Dwarf pawpaw", cleandata$clean_plantSp) #could probably just leave plant names lower case and use fewer gsubs
cleandata$clean_plantSp= gsub("dwarf pawpaw", "Dwarf pawpaw", cleandata$clean_plantSp)
cleandata$clean_plantSp= gsub("baby paw paw", "Dwarf pawpaw", cleandata$clean_plantSp)
cleandata$clean_plantSp= gsub("eastern red bud", "Eastern redbud", cleandata$clean_plantSp)
cleandata$clean_plantSp= gsub("eastern red bud ", "Eastern redbud", cleandata$clean_plantSp)
cleandata$clean_plantSp= gsub("eastern redbud", "Eastern redbud", cleandata$clean_plantSp)
cleandata$clean_plantSp= gsub("redbud", "Eastern redbud", cleandata$clean_plantSp) #causing an error
cleandata$clean_plantSp= gsub("flowering dogwood", "Flowering dogwood", cleandata$clean_plantSp)
cleandata$clean_plantSp= gsub("flowering dogwood ", "Flowering dogwood", cleandata$clean_plantSp)
cleandata$clean_plantSp= gsub("fraser magnolia", "Fraser magnolia", cleandata$clean_plantSp)
cleandata$clean_plantSp= gsub("fringe tree", "Fringetree", cleandata$clean_plantSp)
cleandata$clean_plantSp= gsub("fringetree", "Fringetree", cleandata$clean_plantSp)  
cleandata$clean_plantSp= gsub("great rhododendron", "Great rhododendron", cleandata$clean_plantSp) 
cleandata$clean_plantSp= gsub("hazelnut", "American hazelnut", cleandata$clean_plantSp) 
cleandata$clean_plantSp= gsub("hazlenut", "American hazelnut", cleandata$clean_plantSp) 
cleandata$clean_plantSp= gsub("maple-leaved viburnum", "Mapleleaf viburnum", cleandata$clean_plantSp)
cleandata$clean_plantSp= gsub("mapleleaf viburnum", "Mapleleaf viburnum", cleandata$clean_plantSp)
cleandata$clean_plantSp= gsub("mapleleaf viburnum ", "Mapleleaf viburnum", cleandata$clean_plantSp)
cleandata$clean_plantSp= gsub("mapleleaf-viburnum", "Mapleleaf viburnum", cleandata$clean_plantSp)
cleandata$clean_plantSp= gsub("maple-leaf viburnum ", "Mapleleaf viburnum", cleandata$clean_plantSp)
cleandata$clean_plantSp= gsub("mountain laurel", "Mountain laurel", cleandata$clean_plantSp)
cleandata$clean_plantSp= gsub("mountain maple", "Mountain maple", cleandata$clean_plantSp)
cleandata$clean_plantSp= gsub("mucslewood", "Musclewood", cleandata$clean_plantSp)
cleandata$clean_plantSp= gsub("muscewood", "Musclewood", cleandata$clean_plantSp)
cleandata$clean_plantSp= gsub("muscle wood ", "Musclewood", cleandata$clean_plantSp)
cleandata$clean_plantSp= gsub("musclewood", "Musclewood", cleandata$clean_plantSp)
cleandata$clean_plantSp= gsub("mulberry", "White mulberry", cleandata$clean_plantSp)
cleandata$clean_plantSp= gsub("white mulberry", "White mulberry", cleandata$clean_plantSp)
cleandata$clean_plantSp= gsub("paw paw", "Pawpaw", cleandata$clean_plantSp)
cleandata$clean_plantSp= gsub("paw-paw", "Pawpaw", cleandata$clean_plantSp)
cleandata$clean_plantSp= gsub("pawpaw", "Pawpaw", cleandata$clean_plantSp)
cleandata$clean_plantSp= gsub("pawpaw", "Pin oak", cleandata$clean_plantSp)
cleandata$clean_plantSp= gsub("red maple", "Red maple", cleandata$clean_plantSp)
cleandata$clean_plantSp= gsub("red maple ", "Red maple", cleandata$clean_plantSp)
cleandata$clean_plantSp= gsub("red oak", "Red oak", cleandata$clean_plantSp)
cleandata$clean_plantSp= gsub("red oak ", "Red oak", cleandata$clean_plantSp)
cleandata$clean_plantSp= gsub("sassafras", "Sassafras", cleandata$clean_plantSp)
cleandata$clean_plantSp= gsub("serviceberry", "Serviceberry", cleandata$clean_plantSp)
cleandata$clean_plantSp= gsub("sour wood", "Sourwood", cleandata$clean_plantSp)
cleandata$clean_plantSp= gsub("sourwood", "Sourwood", cleandata$clean_plantSp)
cleandata$clean_plantSp= gsub("sourwood ", "Sourwood", cleandata$clean_plantSp)
cleandata$clean_plantSp= gsub("spice bush", "Spicebush", cleandata$clean_plantSp)
cleandata$clean_plantSp= gsub("spicebush", "Spicebush", cleandata$clean_plantSp)
cleandata$clean_plantSp= gsub("spicebush ", "Spicebush", cleandata$clean_plantSp)
cleandata$clean_plantSp= gsub("striped maple", "Striped maple", cleandata$clean_plantSp)      
cleandata$clean_plantSp= gsub("alternate-leafed dogwood", "Alternate-leaved dogwood", cleandata$clean_plantSp)  
cleandata$clean_plantSp= gsub("black cherry", "Black cherry", cleandata$clean_plantSp)
cleandata$clean_plantSp= gsub("black locust", "Black locust", cleandata$clean_plantSp)
cleandata$clean_plantSp= gsub("cucumber magnolia", "Cucumber magnolia", cleandata$clean_plantSp)
cleandata$clean_plantSp= gsub("elm", "Elm", cleandata$clean_plantSp)
cleandata$clean_plantSp= gsub("elum", "Elm", cleandata$clean_plantSp)
cleandata$clean_plantSp= gsub("chinkapin", "White oak", cleandata$clean_plantSp)
cleandata$clean_plantSp= gsub("white oak", "White oak", cleandata$clean_plantSp)
cleandata$clean_plantSp= gsub("flame azalea", "Flame azalea", cleandata$clean_plantSp)
cleandata$clean_plantSp= gsub("highbush blueberry", "Highbush blueberry", cleandata$clean_plantSp)
cleandata$clean_plantSp= gsub("hop hornbeam", "Hop hornbeam", cleandata$clean_plantSp)
cleandata$clean_plantSp= gsub("mountain holly", "Mountain holly", cleandata$clean_plantSp)
cleandata$clean_plantSp= gsub("pignut hickory", "Pignut hickory", cleandata$clean_plantSp)
cleandata$clean_plantSp= gsub("pin cherry", "Pin cherry", cleandata$clean_plantSp)
cleandata$clean_plantSp= gsub("russian olive", "Russian olive", cleandata$clean_plantSp)
cleandata$clean_plantSp= gsub("sweet pepper bush", "Sweet pepperbush", cleandata$clean_plantSp)
cleandata$clean_plantSp= gsub("shagbark hickory", "Shagbark hickory", cleandata$clean_plantSp)
cleandata$clean_plantSp= gsub("tuliptree", "Tuliptree", cleandata$clean_plantSp)
cleandata$clean_plantSp= gsub("unid. ash", "Unid. ash", cleandata$clean_plantSp)
cleandata$clean_plantSp= gsub("unid. cherry", "Unid. cherry", cleandata$clean_plantSp)
cleandata$clean_plantSp[cleandata$clean_plantSp %in% c('unid. elm', 'unidentified elm')] = "Unid. elm"

cleandata$clean_plantSp= gsub("unid. hickory", "Unid. hickory", cleandata$clean_plantSp)
cleandata$clean_plantSp[cleandata$clean_plantSp == 'maple'] = "Unid. maple"

cleandata$clean_plantSp= gsub("unid. rhododendron", "Unid. rhododendron", cleandata$clean_plantSp)
cleandata$clean_plantSp= gsub("unid willow", "Unid. willow", cleandata$clean_plantSp)
cleandata$clean_plantSp= gsub("white ash", "White ash", cleandata$clean_plantSp)





cleandata$clean_plantSp[cleandata$clean_plantSp %in% c("frsp", "list", "musclewood (possible id: sweetgum)", "musclewood? maple is correct id", 
                                                       "musclewood?, sweetgum correct id, i think.", "quer","rhsp", "station", "staton", "sweet elm", "sweetgum? maple i think is correct id",
                                                       "sweetgum? maple is correct id i think.", "sweetgum? maple is correct id i think.", "sweetgum? musclewood correct id", 
                                                       "sweetgum? musclewood is correct id", "sweetgum? musclewood is correct id i believe",  "syor", "test",
                                                       "unid. rubus", "unidentified", "unidentified ", "unidentified sp", "vasp")] = "Unidentified"


                                                                                                                                                                                                                                                                                                                                                    ifelse (cleandata$plantSp %in% c("american chestnut"),"American chestnut",
                                                                                                                                                                                                                                                                                                                                                            ifelse (cleandata$plantSp %in% c("american holly", "american holly "), "American holly",
                                                                                                                                                                                                                                                                                                                                                                    ifelse (cleandata$plantSp %in% c("american hornbeam", "american hornbeam ", "carpinus caroliniana"), "American hornbeam", 
                                                                                                                                                                                                                                                                                                                                                                            ifelse (cleandata$plantSp %in% c("american sycamore"), "American sycamore",
                                                                                                                                                                                                                                                                                                                                                                                    ifelse (cleandata$plantSp %in% c("arsp", "devil's walking stick", "devil's walkingstick","devil's-walking-sticl", "devils claw", "devils walking stick", "devils-walkingstick"), "Devil's walkingstick",
                                                                                                                                                                                                                                                                                                                                                                                            ifelse (cleandata$plantSp %in% c("bear huckleberry"), "Bear huckleberry",
                                                                                                                                                                                                                                                                                                                                                                                                    ifelse (cleandata$plantSp %in% c("bitternut hickory", "butternut hickory"), "Bitternut hickory",
                                                                                                                                                                                                                                                                                                                                                                                                            ifelse (cleandata$plantSp %in% c("black gum"), "Black gum",
                                                                                                                                                                                                                                                                                                                                                                                                                    ifelse (cleandata$plantSp %in% c("black oak"), "Black oak",
                                                                                                                                                                                                                                                                                                                                                                                                                            ifelse (cleandata$plantSp %in% c("black willow", "black willow ", "willow", "wilow"), "Black willow",
                                                                                                                                                                                                                                                                                                                                                                                                                                    ifelse (cleandata$plantSp %in% c("box elder", "box elder "), "Box elder",
                                                                                                                                                                                                                                                                                                                                                                                                                                            ifelse (cleandata$plantSp %in% c("buffalo nut"), "Buffalo nut",
                                                                                                                                                                                                                                                                                                                                                                                                                                                    ifelse (cleandata$plantSp %in% c("carolina ash", "carolina ash "), "Carolina ash",
                                                                                                                                                                                                                                                                                                                                                                                                                                                            ifelse (cleandata$plantSp %in% c("carolina silver", "carolina silver bell", "carolina silverbell", "silverbell"), "Carolina silverbell",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ifelse (cleandata$plantSp %in% c("chalk maple"), "Chalk maple",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ifelse (cleandata$plantSp %in% c("chestnut oak"), "Chestnut oak",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ifelse (cleandata$plantSp %in% c("common persimmon", "persimmon", "perssimon"), "Common persimmon",  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ifelse (cleandata$plantSp %in% c("dwarf paw paw", "dwarf pawpaw", "baby paw paw"), "Dwarf pawpaw",   
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ifelse (cleandata$plantSp %in% c("eastern red bud", "eastern red bud ", "eastern redbud", "redbud"), "Eastern redbud",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ifelse (cleandata$plantSp %in% c("flowering dogwood", "flowering dogwood "), "Flowering dogwood",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ifelse (cleandata$plantSp %in% c("fraser magnolia"), "Fraser magnolia",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ifelse (cleandata$plantSp %in% c("fringe tree", "fringetree"), "Fringetree",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ifelse (cleandata$plantSp %in% c("great rhododendron"), "Great rhododendron",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ifelse (cleandata$plantSp %in% c("hazelnut", "hazlenut"), "American hazelnut",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ifelse (cleandata$plantSp %in% c("maple-leaved viburnum", "mapleleaf viburnum", "mapleleaf viburnum ", "mapleleaf-viburnum", "maple-leaf viburnum "), "Mapleleaf viburnum",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ifelse (cleandata$plantSp %in% c("mountain laurel"), "Mountain laurel",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ifelse (cleandata$plantSp %in% c("mucslewood", "muscewood", "muscle wood ", "musclewood"), "Musclewood",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ifelse (cleandata$plantSp %in% c("mulberry", "white mulberry"), "White mulberry", 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ifelse (cleandata$plantSp %in% c("paw paw", "paw-paw", "pawpaw"), "Pawpaw", 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ifelse (cleandata$plantSp %in% c("pin oak"), "Pin oak", 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ifelse (cleandata$plantSp %in% c("red maple", "red maple "), "Red maple", 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ifelse (cleandata$plantSp %in% c("red oak", "red oak "), "Red oak", 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ifelse (cleandata$plantSp %in% c("sassafras"), "Sassafras", 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ifelse (cleandata$plantSp %in% c("serviceberry"), "Serviceberry", 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ifelse (cleandata$plantSp %in% c("sour wood", "sourwood", "sourwood "), "Sourwood", 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ifelse (cleandata$plantSp %in% c("spice bush", "spicebush", "spicebush "), "Spicebush",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ifelse (cleandata$plantSp %in% c("striped maple"), "Striped maple", 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ifelse (cleandata$plantSp %in% c("sweet birch"), "Sweet birch",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ifelse (cleandata$plantSp %in% c("sweet gum", "sweet gum ", "sweet gun", "sweetgum"), "Sweet gum",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ifelse (cleandata$plantSp %in% c("tulip poplar", "tulip poplar ", "tulip tree", "tuliptree", "tuliptree "), "Tuliptree", 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ifelse (cleandata$plantSp %in% c("winged elm"), "Winged elm",  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ifelse (cleandata$plantSp %in% c("witch hazel"), "Witch hazel", 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ifelse (cleandata$plantSp %in% c("yellow birch"), "Yellow birch", 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ifelse (cleandata$plantSp %in% c("yellow buckeye"), "Yellow buckeye", "UNID")))))))))))))))))))))))))))))))))))))))))))))))))                                                                                                                                                                                                                                                                                                                                               ifelse (cleandata$plantSp %in% c("tulip poplar", "tulip poplar ", "tulip tree", "tuliptree", "tuliptree "), "Tuliptree",                                                                                                                                                                                                                                                                                                                                       ifelse (cleandata$plantSp %in% c("winged elm"), "Winged elm",  
                                                                                                                                                                                                                                                                                                                                                                                                    ifelse (cleandata$plantSp %in% c("witch hazel"), "Witch hazel", 
                                                                                                                                                                                                                                                                                                                                                                                                            ifelse (cleandata$plantSp %in% c("yellow birch"), "Yellow birch", 
 
